const express = require('express');
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const ClientProject = require('../models/ClientProject');
const { auth, adminOnly } = require('../middleware/auth');

const router = express.Router();

// ═══════════════════════════════════════════
// TEMPLATE REGISTRY
// Maps app slugs to their git repos and type
// ═══════════════════════════════════════════
const TEMPLATES = {
  'simple-website': {
    repo: 'https://github.com/3dhuboz/SimpleWebsite.git',
    type: 'standalone',
    defaultBranch: 'main',
    description: 'White-label e-commerce website (React/Firebase/Vite)'
  },
  'social-ai-studio': {
    repo: 'https://github.com/3dhuboz/Penny-Wise-IT.git',
    type: 'pennywise-module',
    defaultBranch: 'main',
    enabledApps: 'social-ai-studio',
    description: 'SocialAI Studio (Pennywise module)'
  },
  'foodtruc': {
    repo: 'https://github.com/3dhuboz/Penny-Wise-IT.git',
    type: 'pennywise-module',
    defaultBranch: 'main',
    enabledApps: 'foodtruc',
    description: 'Food Truck ordering app (Pennywise module)'
  },
  'wirez': {
    repo: 'https://github.com/3dhuboz/Penny-Wise-IT.git',
    type: 'pennywise-module',
    defaultBranch: 'main',
    enabledApps: 'wirez',
    description: 'Wirez electrician workflow (Pennywise module)'
  },
  'autohue': {
    repo: 'https://github.com/3dhuboz/Penny-Wise-IT.git',
    type: 'pennywise-module',
    defaultBranch: 'main',
    enabledApps: 'autohue',
    description: 'AutoHue car photo sorter (Pennywise module)'
  }
};

// ═══════════════════════════════════════════
// SAMPLE DATA for each app type
// ═══════════════════════════════════════════
function getSampleEnv(template, project) {
  const brand = project.businessName || project.projectName;
  const tagline = project.whiteLabel?.tagline || `Welcome to ${brand}`;
  const primaryColor = project.whiteLabel?.primaryColor || '#3b82f6';

  if (template.type === 'standalone') {
    // SimpleWebsite uses Firebase — provide sample .env.local
    return `# ${brand} — Auto-generated by Penny Wise I.T Scaffold
# Update these values with real credentials before deploying

VITE_APP_NAME="${brand}"
VITE_APP_TAGLINE="${tagline}"
VITE_PRIMARY_COLOR="${primaryColor}"

# Firebase (create a new project at https://console.firebase.google.com)
VITE_FIREBASE_API_KEY=your-api-key
VITE_FIREBASE_AUTH_DOMAIN=your-project.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=your-project-id
VITE_FIREBASE_STORAGE_BUCKET=your-project.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
VITE_FIREBASE_APP_ID=your-app-id

# Square Payments (https://developer.squareup.com)
VITE_SQUARE_APP_ID=sandbox-your-app-id
VITE_SQUARE_LOCATION_ID=your-location-id
VITE_SQUARE_ENVIRONMENT=sandbox

# Google Gemini AI (for SocialAI add-on)
VITE_GEMINI_API_KEY=your-gemini-key

# Penny Wise I.T License (for SocialAI add-on validation)
VITE_LICENSE_KEY=
VITE_LICENSE_API_URL=https://pennywiseit.com.au/api/marketplace/validate-license
`;
  }

  // Pennywise module — .env file
  const enabledApps = project.apps?.map(a => a.slug).join(',') || template.enabledApps;
  return `# ${brand} — Auto-generated by Penny Wise I.T Scaffold
# Update these values with real credentials before deploying

NODE_ENV=development
PORT=5000

# Client mode — isolates this as a client deployment
CLIENT_MODE=true
ENABLED_APPS=${enabledApps}
BRAND_NAME="${brand}"
BRAND_TAGLINE="${tagline}"
PRIMARY_COLOR=${primaryColor}

# MongoDB (create a free cluster at https://cloud.mongodb.com)
MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/${brand.toLowerCase().replace(/[^a-z0-9]/g, '-')}?retryWrites=true&w=majority

# Auth
JWT_SECRET=change-me-to-a-random-string
ADMIN_EMAIL=admin@${brand.toLowerCase().replace(/[^a-z0-9]/g, '')}.com.au
ADMIN_PASSWORD=TempPass123!

# Square Payments
SQUARE_ACCESS_TOKEN=
SQUARE_LOCATION_ID=
SQUARE_ENVIRONMENT=sandbox

# AI
GEMINI_API_KEY=
`;
}

function getSampleReadme(project) {
  const brand = project.businessName || project.projectName;
  return `# ${brand}

> Auto-scaffolded by [Penny Wise I.T](https://pennywiseit.com.au) on ${new Date().toLocaleDateString('en-AU')}

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Copy and configure environment variables:
   - Edit \`.env.local\` (or \`.env\`) with your credentials
   - See the file for required API keys

3. Start development server:
   \`\`\`bash
   npm run dev
   \`\`\`

4. Open in browser: http://localhost:3000 (or http://localhost:5173 for Vite)

## Deployment

This project is managed by Penny Wise I.T. Contact your admin for deployment.

## Branding

- **Business Name:** ${brand}
- **Tagline:** ${project.whiteLabel?.tagline || 'Update in admin'}
- **Primary Color:** ${project.whiteLabel?.primaryColor || '#3b82f6'}
`;
}

// ═══════════════════════════════════════════
// SCAFFOLD ENDPOINT
// POST /api/scaffold/:projectId
// ═══════════════════════════════════════════
router.post('/:projectId', auth, adminOnly, async (req, res) => {
  try {
    // Only works locally — need filesystem + git access
    if (process.env.VERCEL || process.env.NODE_ENV === 'production') {
      return res.status(400).json({
        message: 'Scaffolding only works when running locally. Start the server on your dev machine.'
      });
    }

    const project = await ClientProject.findById(req.params.projectId)
      .populate('client', 'firstName lastName email company');
    if (!project) return res.status(404).json({ message: 'Project not found' });

    // Determine primary app template
    const appSlugs = project.apps?.map(a => a.slug) || [];
    if (appSlugs.length === 0) {
      return res.status(400).json({ message: 'No apps selected for this project. Add apps first.' });
    }

    // Use first app's template (primary app)
    const primarySlug = appSlugs[0];
    const template = TEMPLATES[primarySlug];
    if (!template) {
      return res.status(400).json({ message: `No template found for app: ${primarySlug}` });
    }

    // Determine target directory
    const baseDir = process.env.CLIENT_PROJECTS_BASE_DIR
      || path.join(require('os').homedir(), 'OneDrive', 'Desktop', 'Business Folders');
    const clientName = project.businessName || project.projectName;
    const safeName = clientName.replace(/[<>:"/\\|?*]/g, '').trim();
    const projectDir = path.join(baseDir, safeName, 'App', safeName.replace(/\s+/g, '-'));

    // Check if already scaffolded
    if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length > 0) {
      // Directory exists and has files — just update the localProjectPath
      project.localProjectPath = projectDir;
      await project.save();
      return res.json({
        message: `Project folder already exists at ${projectDir}. Path linked.`,
        localProjectPath: projectDir,
        alreadyExists: true
      });
    }

    // Create directory structure
    fs.mkdirSync(projectDir, { recursive: true });

    // Clone template repo
    console.log(`[Scaffold] Cloning ${template.repo} → ${projectDir}`);
    try {
      execSync(`git clone --depth 1 --branch ${template.defaultBranch} "${template.repo}" "${projectDir}"`, {
        stdio: 'pipe',
        timeout: 120000 // 2 minute timeout
      });
    } catch (cloneErr) {
      // Clean up empty dir on failure
      try { fs.rmSync(projectDir, { recursive: true, force: true }); } catch (e) {}
      return res.status(500).json({
        message: 'Git clone failed. Check your internet connection and git credentials.',
        error: cloneErr.stderr?.toString() || cloneErr.message
      });
    }

    // Remove the .git directory so it's a fresh project (not linked to template repo)
    const gitDir = path.join(projectDir, '.git');
    if (fs.existsSync(gitDir)) {
      fs.rmSync(gitDir, { recursive: true, force: true });
    }

    // Initialize fresh git repo for the client
    try {
      execSync('git init', { cwd: projectDir, stdio: 'pipe' });
      execSync('git add -A', { cwd: projectDir, stdio: 'pipe' });
      execSync(`git commit -m "Initial scaffold for ${clientName}"`, { cwd: projectDir, stdio: 'pipe' });
    } catch (gitErr) {
      console.warn('[Scaffold] Git init warning:', gitErr.message);
    }

    // Write environment config
    const envContent = getSampleEnv(template, project);
    const envFile = template.type === 'standalone' ? '.env.local' : '.env';
    fs.writeFileSync(path.join(projectDir, envFile), envContent, 'utf8');

    // Write README
    fs.writeFileSync(path.join(projectDir, 'README.md'), getSampleReadme(project), 'utf8');

    // Write a scaffold metadata file
    const scaffoldMeta = {
      scaffoldedAt: new Date().toISOString(),
      scaffoldedBy: 'Penny Wise I.T',
      template: primarySlug,
      templateRepo: template.repo,
      clientName: clientName,
      projectId: project._id.toString(),
      apps: appSlugs
    };
    fs.writeFileSync(
      path.join(projectDir, '.pennywise.json'),
      JSON.stringify(scaffoldMeta, null, 2),
      'utf8'
    );

    // Update project with local path
    project.localProjectPath = projectDir;

    // Mark the first checklist item as done if it exists
    if (project.setupChecklist?.length > 0) {
      const createStep = project.setupChecklist.find(s =>
        s.step.toLowerCase().includes('create customer')
      );
      if (createStep && !createStep.completed) {
        createStep.completed = true;
        createStep.completedAt = new Date();
        createStep.notes = 'Auto-completed by scaffold';
      }
    }

    await project.save();

    console.log(`[Scaffold] ✓ Project scaffolded at ${projectDir}`);

    res.json({
      message: `Project scaffolded successfully!`,
      localProjectPath: projectDir,
      template: primarySlug,
      templateDescription: template.description,
      alreadyExists: false
    });

  } catch (err) {
    console.error('[Scaffold] Error:', err);
    res.status(500).json({ message: 'Scaffold failed', error: err.message });
  }
});

// GET scaffold status for a project
router.get('/:projectId/status', auth, adminOnly, async (req, res) => {
  try {
    const project = await ClientProject.findById(req.params.projectId);
    if (!project) return res.status(404).json({ message: 'Project not found' });

    const localPath = project.localProjectPath;
    if (!localPath) {
      return res.json({ scaffolded: false, message: 'No local project path set' });
    }

    const exists = fs.existsSync(localPath);
    const hasFiles = exists && fs.readdirSync(localPath).length > 0;
    const hasPennywiseMeta = exists && fs.existsSync(path.join(localPath, '.pennywise.json'));

    let meta = null;
    if (hasPennywiseMeta) {
      try {
        meta = JSON.parse(fs.readFileSync(path.join(localPath, '.pennywise.json'), 'utf8'));
      } catch (e) {}
    }

    res.json({
      scaffolded: hasFiles,
      exists,
      hasFiles,
      hasPennywiseMeta,
      meta,
      localPath
    });
  } catch (err) {
    res.status(500).json({ message: 'Status check failed', error: err.message });
  }
});

// GET available templates
router.get('/templates/list', auth, adminOnly, (req, res) => {
  const templates = Object.entries(TEMPLATES).map(([slug, t]) => ({
    slug,
    description: t.description,
    type: t.type,
    repo: t.repo
  }));
  res.json(templates);
});

module.exports = router;
